/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/robalaban/nordigen-go/go"
)

func main() {
	log.Printf("Server started")

	AccountsApiService := openapi.NewAccountsApiService()
	AccountsApiController := openapi.NewAccountsApiController(AccountsApiService)

	AgreementsApiService := openapi.NewAgreementsApiService()
	AgreementsApiController := openapi.NewAgreementsApiController(AgreementsApiService)

	InstitutionsApiService := openapi.NewInstitutionsApiService()
	InstitutionsApiController := openapi.NewInstitutionsApiController(InstitutionsApiService)

	RequisitionsApiService := openapi.NewRequisitionsApiService()
	RequisitionsApiController := openapi.NewRequisitionsApiController(RequisitionsApiService)

	TokenApiService := openapi.NewTokenApiService()
	TokenApiController := openapi.NewTokenApiController(TokenApiService)

	router := openapi.NewRouter(AccountsApiController, AgreementsApiController, InstitutionsApiController, RequisitionsApiController, TokenApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
