/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nordigen

import (
	"context"
	"errors"
	"net/http"
)

// RequisitionsApiService is a service that implements the logic for the RequisitionsApiServicer
// This service should implement the business logic for every endpoint for the RequisitionsApi API.
// Include any external packages or services that will be required by this service.
type RequisitionsApiService struct {
}

// NewRequisitionsApiService creates a default api service
func NewRequisitionsApiService() RequisitionsApiServicer {
	return &RequisitionsApiService{}
}

// DeleteRequisitionByIdV2 - 
func (s *RequisitionsApiService) DeleteRequisitionByIdV2(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update DeleteRequisitionByIdV2 with the required logic for this service method.
	// Add api_requisitions_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(400, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(404, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(404, map[string]interface{}{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteRequisitionByIdV2 method not implemented")
}

// RequisitionById - 
func (s *RequisitionsApiService) RequisitionById(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update RequisitionById with the required logic for this service method.
	// Add api_requisitions_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, RequisitionV2{}) or use other options such as http.Ok ...
	//return Response(200, RequisitionV2{}), nil

	//TODO: Uncomment the next line to return response Response(404, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(404, map[string]interface{}{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RequisitionById method not implemented")
}

// RequisitionCreated - 
func (s *RequisitionsApiService) RequisitionCreated(ctx context.Context, requisitionV2 RequisitionV2) (ImplResponse, error) {
	// TODO - update RequisitionCreated with the required logic for this service method.
	// Add api_requisitions_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, SpectacularRequisitionV2{}) or use other options such as http.Ok ...
	//return Response(201, SpectacularRequisitionV2{}), nil

	//TODO: Uncomment the next line to return response Response(400, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(400, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(404, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(404, map[string]interface{}{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RequisitionCreated method not implemented")
}

// RetrieveAllRequisitions - 
func (s *RequisitionsApiService) RetrieveAllRequisitions(ctx context.Context, limit int32, offset int32) (ImplResponse, error) {
	// TODO - update RetrieveAllRequisitions with the required logic for this service method.
	// Add api_requisitions_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, PaginatedRequisitionV2List{}) or use other options such as http.Ok ...
	//return Response(200, PaginatedRequisitionV2List{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RetrieveAllRequisitions method not implemented")
}
