/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nordigen

import (
	"context"
	"errors"
	"net/http"
)

// AccountsApiService is a service that implements the logic for the AccountsApiServicer
// This service should implement the business logic for every endpoint for the AccountsApi API.
// Include any external packages or services that will be required by this service.
type AccountsApiService struct {
}

// NewAccountsApiService creates a default api service
func NewAccountsApiService() AccountsApiServicer {
	return &AccountsApiService{}
}

// RetrieveAccountBalances - 
func (s *AccountsApiService) RetrieveAccountBalances(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update RetrieveAccountBalances with the required logic for this service method.
	// Add api_accounts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InlineResponse200{}) or use other options such as http.Ok ...
	//return Response(200, InlineResponse200{}), nil

	//TODO: Uncomment the next line to return response Response(400, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(400, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(401, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(401, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(403, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(403, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(404, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(404, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(409, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(409, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(429, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(429, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(500, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(500, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(503, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(503, map[string]interface{}{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RetrieveAccountBalances method not implemented")
}

// RetrieveAccountDetails - 
func (s *AccountsApiService) RetrieveAccountDetails(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update RetrieveAccountDetails with the required logic for this service method.
	// Add api_accounts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InlineResponse2001{}) or use other options such as http.Ok ...
	//return Response(200, InlineResponse2001{}), nil

	//TODO: Uncomment the next line to return response Response(400, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(400, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(401, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(401, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(403, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(403, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(404, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(404, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(409, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(409, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(429, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(429, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(500, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(500, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(503, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(503, map[string]interface{}{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RetrieveAccountDetails method not implemented")
}

// RetrieveAccountMetadata - 
func (s *AccountsApiService) RetrieveAccountMetadata(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update RetrieveAccountMetadata with the required logic for this service method.
	// Add api_accounts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, AccountV2{}) or use other options such as http.Ok ...
	//return Response(200, AccountV2{}), nil

	//TODO: Uncomment the next line to return response Response(404, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(404, map[string]interface{}{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RetrieveAccountMetadata method not implemented")
}

// RetrieveAccountTransactions - 
func (s *AccountsApiService) RetrieveAccountTransactions(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update RetrieveAccountTransactions with the required logic for this service method.
	// Add api_accounts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InlineResponse2002{}) or use other options such as http.Ok ...
	//return Response(200, InlineResponse2002{}), nil

	//TODO: Uncomment the next line to return response Response(400, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(400, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(401, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(401, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(403, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(403, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(404, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(404, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(409, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(409, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(429, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(429, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(500, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(500, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(503, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(503, map[string]interface{}{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RetrieveAccountTransactions method not implemented")
}
