/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nordigen

type BalanceAmount struct {

	Amount string `json:"amount,omitempty"`

	Currency string `json:"currency,omitempty"`
}

// AssertBalanceAmountRequired checks if the required fields are not zero-ed
func AssertBalanceAmountRequired(obj BalanceAmount) error {
	return nil
}

// AssertRecurseBalanceAmountRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BalanceAmount (e.g. [][]BalanceAmount), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBalanceAmountRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBalanceAmount, ok := obj.(BalanceAmount)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBalanceAmountRequired(aBalanceAmount)
	})
}
