/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nordigen

type InlineResponse2001Account struct {

	ResourceId string `json:"resourceId,omitempty"`

	Iban string `json:"iban,omitempty"`

	Currency string `json:"currency,omitempty"`

	OwnerName string `json:"ownerName,omitempty"`

	Name string `json:"name,omitempty"`

	Product string `json:"product,omitempty"`

	CashAccountType string `json:"cashAccountType,omitempty"`
}

// AssertInlineResponse2001AccountRequired checks if the required fields are not zero-ed
func AssertInlineResponse2001AccountRequired(obj InlineResponse2001Account) error {
	return nil
}

// AssertRecurseInlineResponse2001AccountRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2001Account (e.g. [][]InlineResponse2001Account), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2001AccountRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2001Account, ok := obj.(InlineResponse2001Account)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2001AccountRequired(aInlineResponse2001Account)
	})
}
