/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nordigen

// SpectacularJwtObtain - Obtain new JWT pair.
type SpectacularJwtObtain struct {

	Password string `json:"password"`

	// Your access token
	Access string `json:"access,omitempty"`

	// Access token expires in seconds
	AccessExpires int32 `json:"access_expires,omitempty"`

	// Your refresh token
	Refresh string `json:"refresh,omitempty"`

	// Refresh token expires in seconds
	RefreshExpires int32 `json:"refresh_expires,omitempty"`
}

// AssertSpectacularJwtObtainRequired checks if the required fields are not zero-ed
func AssertSpectacularJwtObtainRequired(obj SpectacularJwtObtain) error {
	elements := map[string]interface{}{
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseSpectacularJwtObtainRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SpectacularJwtObtain (e.g. [][]SpectacularJwtObtain), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSpectacularJwtObtainRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSpectacularJwtObtain, ok := obj.(SpectacularJwtObtain)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSpectacularJwtObtainRequired(aSpectacularJwtObtain)
	})
}
