/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nordigen

type InlineResponse2002TransactionsPendingTransactionAmount struct {

	Currency string `json:"currency,omitempty"`

	Amount string `json:"amount,omitempty"`
}

// AssertInlineResponse2002TransactionsPendingTransactionAmountRequired checks if the required fields are not zero-ed
func AssertInlineResponse2002TransactionsPendingTransactionAmountRequired(obj InlineResponse2002TransactionsPendingTransactionAmount) error {
	return nil
}

// AssertRecurseInlineResponse2002TransactionsPendingTransactionAmountRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2002TransactionsPendingTransactionAmount (e.g. [][]InlineResponse2002TransactionsPendingTransactionAmount), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2002TransactionsPendingTransactionAmountRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2002TransactionsPendingTransactionAmount, ok := obj.(InlineResponse2002TransactionsPendingTransactionAmount)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2002TransactionsPendingTransactionAmountRequired(aInlineResponse2002TransactionsPendingTransactionAmount)
	})
}
