/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nordigen

type InlineResponse2002TransactionsPending struct {

	TransactionAmount InlineResponse2002TransactionsPendingTransactionAmount `json:"transactionAmount,omitempty"`

	ValueDate string `json:"valueDate,omitempty"`

	RemittanceInformationUnstructuredArray string `json:"remittanceInformationUnstructuredArray,omitempty"`
}

// AssertInlineResponse2002TransactionsPendingRequired checks if the required fields are not zero-ed
func AssertInlineResponse2002TransactionsPendingRequired(obj InlineResponse2002TransactionsPending) error {
	if err := AssertInlineResponse2002TransactionsPendingTransactionAmountRequired(obj.TransactionAmount); err != nil {
		return err
	}
	return nil
}

// AssertRecurseInlineResponse2002TransactionsPendingRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2002TransactionsPending (e.g. [][]InlineResponse2002TransactionsPending), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2002TransactionsPendingRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2002TransactionsPending, ok := obj.(InlineResponse2002TransactionsPending)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2002TransactionsPendingRequired(aInlineResponse2002TransactionsPending)
	})
}
