/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nordigen

type InlineResponse2002Transactions struct {

	Booked []InlineResponse2002TransactionsBooked `json:"booked,omitempty"`

	Pending []InlineResponse2002TransactionsPending `json:"pending,omitempty"`
}

// AssertInlineResponse2002TransactionsRequired checks if the required fields are not zero-ed
func AssertInlineResponse2002TransactionsRequired(obj InlineResponse2002Transactions) error {
	for _, el := range obj.Booked {
		if err := AssertInlineResponse2002TransactionsBookedRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Pending {
		if err := AssertInlineResponse2002TransactionsPendingRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseInlineResponse2002TransactionsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2002Transactions (e.g. [][]InlineResponse2002Transactions), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2002TransactionsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2002Transactions, ok := obj.(InlineResponse2002Transactions)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2002TransactionsRequired(aInlineResponse2002Transactions)
	})
}
