/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nordigen

// EnduserAcceptanceDetails - Represents end-user details.
type EnduserAcceptanceDetails struct {

	UserAgent string `json:"user_agent"`

	IpAddress string `json:"ip_address"`
}

// AssertEnduserAcceptanceDetailsRequired checks if the required fields are not zero-ed
func AssertEnduserAcceptanceDetailsRequired(obj EnduserAcceptanceDetails) error {
	elements := map[string]interface{}{
		"user_agent": obj.UserAgent,
		"ip_address": obj.IpAddress,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseEnduserAcceptanceDetailsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of EnduserAcceptanceDetails (e.g. [][]EnduserAcceptanceDetails), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseEnduserAcceptanceDetailsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aEnduserAcceptanceDetails, ok := obj.(EnduserAcceptanceDetails)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertEnduserAcceptanceDetailsRequired(aEnduserAcceptanceDetails)
	})
}
