/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// AgreementsApiService is a service that implements the logic for the AgreementsApiServicer
// This service should implement the business logic for every endpoint for the AgreementsApi API.
// Include any external packages or services that will be required by this service.
type AgreementsApiService struct {
}

// NewAgreementsApiService creates a default api service
func NewAgreementsApiService() AgreementsApiServicer {
	return &AgreementsApiService{}
}

// AcceptEUA - 
func (s *AgreementsApiService) AcceptEUA(ctx context.Context, id string, enduserAcceptanceDetails EnduserAcceptanceDetails) (ImplResponse, error) {
	// TODO - update AcceptEUA with the required logic for this service method.
	// Add api_agreements_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, EndUserAgreement{}) or use other options such as http.Ok ...
	//return Response(200, EndUserAgreement{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AcceptEUA method not implemented")
}

// CreateEUAV2 - 
func (s *AgreementsApiService) CreateEUAV2(ctx context.Context, endUserAgreement EndUserAgreement) (ImplResponse, error) {
	// TODO - update CreateEUAV2 with the required logic for this service method.
	// Add api_agreements_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, EndUserAgreement{}) or use other options such as http.Ok ...
	//return Response(201, EndUserAgreement{}), nil

	//TODO: Uncomment the next line to return response Response(400, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(400, map[string]interface{}{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateEUAV2 method not implemented")
}

// DeleteEUAByIdV2 - 
func (s *AgreementsApiService) DeleteEUAByIdV2(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update DeleteEUAByIdV2 with the required logic for this service method.
	// Add api_agreements_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(200, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(400, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(400, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(404, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(404, map[string]interface{}{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteEUAByIdV2 method not implemented")
}

// RetrieveAllEUAsForAnEndUserV2 - 
func (s *AgreementsApiService) RetrieveAllEUAsForAnEndUserV2(ctx context.Context, limit int32, offset int32) (ImplResponse, error) {
	// TODO - update RetrieveAllEUAsForAnEndUserV2 with the required logic for this service method.
	// Add api_agreements_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, PaginatedEndUserAgreementList{}) or use other options such as http.Ok ...
	//return Response(200, PaginatedEndUserAgreementList{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RetrieveAllEUAsForAnEndUserV2 method not implemented")
}

// RetrieveEUAByIdV2 - 
func (s *AgreementsApiService) RetrieveEUAByIdV2(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update RetrieveEUAByIdV2 with the required logic for this service method.
	// Add api_agreements_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, EndUserAgreement{}) or use other options such as http.Ok ...
	//return Response(200, EndUserAgreement{}), nil

	//TODO: Uncomment the next line to return response Response(404, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(404, map[string]interface{}{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RetrieveEUAByIdV2 method not implemented")
}
