/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SpectacularJwtRefresh - Refresh Access token.
type SpectacularJwtRefresh struct {

	// Your access token
	Access string `json:"access,omitempty"`

	// Access token expires in seconds
	AccessExpires int32 `json:"access_expires,omitempty"`
}

// AssertSpectacularJwtRefreshRequired checks if the required fields are not zero-ed
func AssertSpectacularJwtRefreshRequired(obj SpectacularJwtRefresh) error {
	return nil
}

// AssertRecurseSpectacularJwtRefreshRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SpectacularJwtRefresh (e.g. [][]SpectacularJwtRefresh), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSpectacularJwtRefreshRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSpectacularJwtRefresh, ok := obj.(SpectacularJwtRefresh)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSpectacularJwtRefreshRequired(aSpectacularJwtRefresh)
	})
}
