/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// RequisitionLinks - RequisitionLinksSerializer.
type RequisitionLinks struct {

	Initiate string `json:"initiate,omitempty"`
}

// AssertRequisitionLinksRequired checks if the required fields are not zero-ed
func AssertRequisitionLinksRequired(obj RequisitionLinks) error {
	return nil
}

// AssertRecurseRequisitionLinksRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequisitionLinks (e.g. [][]RequisitionLinks), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequisitionLinksRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequisitionLinks, ok := obj.(RequisitionLinks)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequisitionLinksRequired(aRequisitionLinks)
	})
}
