/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0 (v2)
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2001Balance struct {

	BalanceType string `json:"balanceType,omitempty"`

	ReferenceDate string `json:"referenceDate,omitempty"`

	BalanceAmount BalanceAmount `json:"balanceAmount,omitempty"`
}

// AssertInlineResponse2001BalanceRequired checks if the required fields are not zero-ed
func AssertInlineResponse2001BalanceRequired(obj InlineResponse2001Balance) error {
	if err := AssertBalanceAmountRequired(obj.BalanceAmount); err != nil {
		return err
	}
	return nil
}

// AssertRecurseInlineResponse2001BalanceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2001Balance (e.g. [][]InlineResponse2001Balance), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2001BalanceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2001Balance, ok := obj.(InlineResponse2001Balance)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2001BalanceRequired(aInlineResponse2001Balance)
	})
}
